# Fuse Instalation Source

binary:
  folder: '/tmp/'

# Fuse Version and Patch
fuse:
  version: '7.2.0'
  patch: '035'
  full_version: '720035'
  maven_version: '00001'

# Patch Fuse Version and Patch
fuse_patch:
  version: '7.2.0'
  patch: '035'
  full_version: '720035'
  maven_version: '00001'

# OS User to install/execute Fuse
user:
  name: 'fuse'
  shell: '/bin/bash'
  homedir: 'True'

# OS Global Variables

# Java Home
java_home: /usr/lib/jvm/jre-1.8.0-openjdk

# Fuse Home
fuse_base: '/opt/fuse7'
fuse_home: '{{ fuse_base }}/latest-{{ esb_name }}'

# Backups Paths
fuse_backup_path: '{{ fuse_base }}/backup'

# Fuse Administrative Users
fuse_users:
  admin:
    username: admin
    password: karaf
    roles:
      - group
      - admin
      - manager
      - viewer
      - systembundles
      - ssh
  deployer:
    username: deployer
    password: deployer
    roles:
      - manager
  guest:
    username: guest
    password: guest
    roles:
      - viewer
  amq:
    username: amq
    password: karaf
    roles:
      - viewer
      - admin

## Setup for Applications and Bundles

fuse_client: '{{ fuse_home }}/bin/client -r 3 -d 10 -u {{ fuse_users.admin.username }} -p {{ fuse_users.admin.password }}'

# Applications Home
app_home: '{{ fuse_base }}/applications'

# Maven Repository
maven_repository_manager: http://rh7server02:8081/repository/maven-public

# Maven Repositories Sample
# maven_repository:
#   -
#     url: 'http://rh7server02:8081/repository/maven-releases'
#     id: 'local.release'
#     extra: ''
#   - url: 'http://rh7server02:8081/repository/maven-snapshots'
#     id: 'local.snapshot'
#     extra: '@snapshots'

# Camel A-MQ Samples from https://github.com/rmarting/camel-amq-samples/tree/karaf-fuse-6.3.0
# Camel CXF Samples from https://github.com/rmarting/fuse-demo/tree/karaf-fuse-6.3.0

# Application List to deploy
applications:
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-consumer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-producer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-forwarder
    version: 1.1.0-SNAPSHOT

# Bundles List to deploy
bundles:
  -
    groupId: com.redhat.fuse.demo
    artifactId: camel-cxfrs
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.fuse.demo
    artifactId: camel-cxf
    version: 1.1.0-SNAPSHOT

# Features List to deploy

features:
  -
    groupId: com.redhat.fuse.demo
    artifactId: fuse-demo-features
    version: 1.1.0-SNAPSHOT
    name: fuse-demo-features

# Application List to undeploy
applications_undeploy:
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-consumer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-producer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-forwarder
    version: 1.1.0-SNAPSHOT

# Bundles List to undeploy
bundles_undeploy:
  -
    groupId: com.redhat.fuse.demo
    artifactId: camel-cxfrs
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.fuse.demo
    artifactId: camel-cxf
    version: 1.1.0-SNAPSHOT

# Features List to undeploy

features_undeploy:
  -
    groupId: com.redhat.fuse.demo
    artifactId: fuse-demo-features
    version: 1.1.0-SNAPSHOT
    name: fuse-demo-features
