---
- name: Fuse Standalone Playbook
  hosts: fuse-lab-environment
  serial: 2
  remote_user: root
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    # Two Fuse Standalone with a Network of Brokers
    - {
        role: fuse-install,
        esb_name: 'esb01',
        port_offset: '0'
      }
    - {
        role: fuse-install,
        esb_name: 'esb02',
        port_offset: '100'
      }
