---
- name: Check if Fuse Service Exists
  stat:
    path: /etc/systemd/system/fuse7-{{ esb_name }}.service
  register: 'fuse7_{{ esb_name | replace("-", "_") }}_service_status'

- name: Stop Fuse Service
  service:
    name: fuse7-{{ esb_name }}
    state: stopped
  when: 'fuse7_{{ esb_name | replace("-", "_") }}_service_status.stat.exists'

- name: Uninstall systemd unit file
  file:
    path: /etc/systemd/system/fuse7-{{ esb_name }}.service
    owner: root
    state: absent
  when: 'fuse7_{{ esb_name | replace("-", "_") }}_service_status.stat.exists'
  notify:
    - reload systemd

- name: Remove current version to installed version
  file:
    path: '{{ fuse_base }}/latest-{{ esb_name }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    state: absent

- name: Uninstall Fuse binaries on Server
  file:
    path: '{{ fuse_base }}/{{ esb_name }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    state: absent
